blank_issues_enabled: false
contact_links:
  - name: ❓ Questions and Support Request
    url: https://github.com/SocketSomeone/nestjs-hot-shots/discussions
    about: Please visit our Discussions page for questions and support requests.
